name: 'fin_copilot'
version: '1.0.0'
config-version: 2

profile: 'fin_copilot'

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fin_copilot:
    staging:
      +materialized: view
      +schema: staging
    analytics:
      +materialized: table
      +schema: analytics
